// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbsizhaygsfiitjfxrby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFic2l6aGF5Z3NmaWl0amZ4cmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjA1NjEsImV4cCI6MjA3MzI5NjU2MX0.T0-UmQqPyX76g5HVKXNbzY_5CW9CmdpPioCUrq15wh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});